#!/bin/bash

options="s:p:h"
function usage()
{
    cat<<EOF
usage: $(basename $0) [-s server] [-p port] [command]

optional arguments:
  -h
             show this help message
  -s server
             autophone server to contact. (default: localhost)
  -p port
             autophone server port to contact (default: 28001)
  command
             command. (default: autophone-status)
             Use autophone-help to get help on autophone commands.
EOF
    exit 0
}

port=28001
server=127.0.0.1

let nshift=0
while getopts $options optname; do
    case $optname in
        h) usage;;
        s) server="$OPTARG"
           let nshift=nshift+2
           ;;
        p) port="$OPTARG"
           let nshift=nshift+2
           ;;
    esac
done
shift $nshift

if [[ -z "$1" ]]; then
    cmd="autophone-status"
elif [[ -z "$server" || -z "$port" ]]; then
     usage
else
    cmd="$@"
fi
echo $cmd | nc $server $port
