#!/bin/bash

if [[ -z "$1" ]]; then
    ap-getstate | grep "=device" | sed -r "s|=device||" | while read n; do
        echo ============== $n ===========
        if [[ $n == nexus-s-* ]]; then
            interface=eth0
        else
            interface=wlan0
        fi
        # Work around failures sequentially invoking adb by placing
        # job in background and waiting for the child process.
        adb -s $(ap-inventory --match=id=$n --output="%(serialno)s") shell "uptime; ifconfig $interface" &
        wait
    done
else
    for m in $@; do
        echo "========== $m =========="
        ssh $m "if [[ -e ~/.profile ]]; then . ~/.profile; else . ~/.bash_profile; fi; ap-wifi"
    done
fi

